# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: 'simpleweb.sln'


- powershell: |
    $utcNow = (Get-Date).ToUniversalTime()
    $year = $utcNow.ToString('yy')
    $dayOfYear = $utcNow.DayOfYear.ToString('D3')
    $secondsOfDay = [int]$utcNow.TimeOfDay.TotalSeconds
    $buildNumber = "{0}{1}" -f $dayOfYear, $secondsOfDay.ToString('00000')
    Write-Host "##vso[task.setvariable variable=BuildVersionNumber]$buildNumber"
    Write-Host "##vso[task.setvariable variable=SemVer]3.0.1-$buildNumber"
  displayName: 'Calculate build version number'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: 'simpleweb.sln'
    arguments: '--configuration Release'
    versioningScheme: byEnvVar
    versionEnvVar: SemVer
    



- task: DotNetCoreCLI@2
  displayName: 'Publish project output'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './simpleweb/simpleweb.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GitHubRelease@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    gitHubConnection: 'MyHealthHier'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(SemVer)'
    assets: 
    isPreRelease: true
    makeLatest: 'false'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- task: UniversalPackages@1
  inputs:
    command: 'publish'
    feed: 'MyHealthHier/BuildArtifacts'
    packageName: 'web-api'
    packageVersion: '$(SemVer)'
    directory: '$(Build.ArtifactStagingDirectory)/publish'
    packageDescription: 'Web API Build'

    
